Repository nathandh/mywebclass-simulation, pull requests merged in 2023-03, with the labels that each got.

#50 W3c validation and File Fixes
  .editorconfig
  .eslintrc.json
  .husky/pre-commit
  .prettierignore
  .prettierrc.json
  package-lock.json
  package.json
  src/content.html
  src/index.html
  src/js/allPages.js
  src/js/contentPage.js
  src/js/main.js
  src/privacy.html
  src/scss/styles.scss
  src/story.html
Labels: Frontend

#51 Fix type in closing <p> tag in privacy.html. Linting and Prettier corrections on latest merged additions.
  src/content.html
  src/js/main.js
  src/privacy.html
Labels: Sprint 1 (03-11-2023 to 03-24-2023), Frontend

#55 Major Content Refactor using ChatGPT and Lighthouse Additions
  .gitignore
  lighthouse/localhost_2023-03-21_18-49-20.report.html
  lighthouse/localhost_2023-03-21_19-04-33.report.html
  lighthouse/localhost_2023-03-22_24-04-20.report.html
  lighthouse/localhost_2023-03-22_24-23-55.report.html
  lighthouse/localhost_2023-03-22_24-28-27.report.html
  lighthouse/localhost_2023-03-22_24-34-08.report.html
  lighthouse/localhost_2023-03-22_24-41-06.report.html
  package-lock.json
  package.json
  src/assets/images/MyWebClass_Promo.jpg
  src/assets/images/logo.jpg
  src/content.html
  src/index.html
  src/js/main.js
  src/privacy.html
  src/scss/styles.scss
  src/story.html
Labels: Frontend

#58 Refactor Webpack configs to allow emitting of robots.txt and sitemap.xml files.
  package-lock.json
  package.json
  src/content.html
  src/index.html
  src/js/main.js
  src/privacy.html
  src/robots.txt
  src/sitemap.xml
  src/story.html
  webpack.config.dev.js
  webpack.config.prod.js
Labels: Bug, Frontend

#56 Update productivity_log.md
  productivity_log.md
Labels: Documentation

#59 Changes to relative './' for index page links
  src/content.html
  src/index.html
  src/privacy.html
  src/story.html
Labels: Frontend

#62 Adds and adjusts various Playwright tests. Brings test count to 32.
  src/content.html
  tests/content.spec.js
  tests/contentPage.spec.js
  tests/crossBrowserSupport.spec.js
  tests/googleAnalytics.spec.js
  tests/homePage.spec.js
  tests/mywebclass_title.spec.js
  tests/ourStoryPage.spec.js
  tests/pageLoadTimes.spec.js
  tests/privacyModal.spec.js
  tests/privacyPolicyPage.spec.js
  tests/privacy_policy.spec.js
  tests/readingTime.spec.js
  tests/scrollOffsetApplied.spec.js
  tests/seoFilesCheck.spec.js
Labels: Frontend

#64 Update privacy.html
  src/content.html
  src/privacy.html
Labels: Sprint 1 (03-11-2023 to 03-24-2023)

#66 Update story.html
  src/story.html
Labels: Sprint 1 (03-11-2023 to 03-24-2023)

#68 Index.html change with formatting and prettier applied
  src/index.html
  tests/privacyModal.spec.js
Labels: Bug, Enhancement, Frontend

#70 Multi-language support for Internationalization. Includes initial Spanish support.
  .eslintrc.json
  package-lock.json
  package.json
  src/.babelrc
  src/content.html
  src/index.html
  src/js/allPages.js
  src/js/contentPage.js
  src/js/i18next.js
  src/js/indexPage.js
  src/js/main.js
  src/locales/de/translation.json
  src/locales/en/translation.json
  src/locales/es/translation.json
  src/locales/fr/translation.json
  src/mainFooter.html
  src/mainNavigation.html
  src/privacy.html
  src/story.html
  tests/homePage.spec.js
  webpack.config.dev.js
  webpack.config.prod.js
Labels: Enhancement, Feature, Sprint 1 (03-11-2023 to 03-24-2023), Frontend

#72 Ensured shared navigation and footer requests were not broken
  src/js/allPages.js
  src/js/i18next.js
Labels: Bug, Frontend

#73 Final added tests and Refactors to add a Work-In-Progress Modal where needed for features not fully implemented.
  src/js/allPages.js
  src/js/i18next.js
  src/js/main.js
  src/mainFooter.html
  src/mainNavigation.html
  tests/internationalization.spec.js
  tests/socialMedia.spec.js
  tests/social_media.spec.js
Labels: Enhancement, Feature, Sprint 1 (03-11-2023 to 03-24-2023), Frontend

#78 Create deployment.md
  deployment.md
Labels: Documentation, Sprint 1 (03-11-2023 to 03-27-2023)

#81 Adjusted WebPack configs for Dev and Prod builds.
  webpack.config.dev.js
  webpack.config.prod.js
Labels: Enhancement, Sprint 1 (03-11-2023 to 03-27-2023), Frontend

#80 Update translation.json
  src/js/i18next.js
  src/locales/de/translation.json
  src/mainNavigation.html
Labels: Enhancement, Sprint 1 (03-11-2023 to 03-27-2023), Frontend

#82 Corrected missing commas in config files as part of Prettier formatti…
  webpack.config.dev.js
  webpack.config.prod.js
Labels: Frontend
